In [1]:
import numpy as np

In [2]:
a1 = np.zeros((2,3),dtype = float)

In [ ]:
a1

array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
a2 = np.ones((3,4))

In [ ]:
a2

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
a3 = np.arange(1,10,0.1)

In [ ]:
a3

array([1. , 1.1, 1.2, 1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2. , 2.1, 2.2,
       2.3, 2.4, 2.5, 2.6, 2.7, 2.8, 2.9, 3. , 3.1, 3.2, 3.3, 3.4, 3.5,
       3.6, 3.7, 3.8, 3.9, 4. , 4.1, 4.2, 4.3, 4.4, 4.5, 4.6, 4.7, 4.8,
       4.9, 5. , 5.1, 5.2, 5.3, 5.4, 5.5, 5.6, 5.7, 5.8, 5.9, 6. , 6.1,
       6.2, 6.3, 6.4, 6.5, 6.6, 6.7, 6.8, 6.9, 7. , 7.1, 7.2, 7.3, 7.4,
       7.5, 7.6, 7.7, 7.8, 7.9, 8. , 8.1, 8.2, 8.3, 8.4, 8.5, 8.6, 8.7,
       8.8, 8.9, 9. , 9.1, 9.2, 9.3, 9.4, 9.5, 9.6, 9.7, 9.8, 9.9])

In [ ]:
a4 = np.eye(6)

In [ ]:
a4

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [ ]:
a4[::-1]

array([[0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0.]])

In [ ]:
np.random.random(10) #生成随机数，模型运算参数的初始化方式一

array([0.81622937, 0.48337013, 0.4472835 , 0.74275662, 0.56632565,
       0.71066252, 0.24653952, 0.41238777, 0.77488333, 0.33893046])

In [ ]:
np.random.random(12)

array([0.35155347, 0.81383269, 0.36289256, 0.49775634, 0.58133518,
       0.18788614, 0.98450339, 0.35409664, 0.6669183 , 0.93557923,
       0.72295367, 0.85107007])

In [ ]:
mu,sigma = 0,0.1

In [ ]:
np.random.normal(mu,sigma,10) #模型参数初始化的方式二

array([ 0.03826443,  0.19648458, -0.12490621,  0.06225442, -0.06040458,
        0.156909  ,  0.04205037, -0.04143591,  0.09366375,  0.05547306])

In [ ]:
a6 = np.array([(1,2),(3,4),(5,6)])

In [ ]:
a6

array([[1, 2],
       [3, 4],
       [5, 6]])

In [ ]:
a6[:,1] #访问数组中的数据

array([2, 4, 6])

In [ ]:
a6[1,:]

array([3, 4])

In [ ]:
a6[0,:]

array([1, 2])

In [ ]:
a6[0][0]  

np.int64(1)

In [ ]:
for i in a6[:][:]:
    for j in i:
        print(j)

1
2
3
4
5
6


In [ ]:
i,j = a6[0]

In [ ]:
print(i,j)

1 2


In [ ]:
j

np.int64(2)

In [ ]:
for i,j in a6:
    print(i,j)

1 2
3 4
5 6


In [ ]:
# ndarray.dim

In [ ]:
a8 = np.array([(1,2),(3,4),(5,6)])

In [ ]:
a8.ndim

2

In [ ]:
a8.size

6

In [ ]:
a8.dtype

dtype('int64')

In [ ]:
print(3 in a8) #检查数据是否存在于数组中

True


In [ ]:
print(10 in a8)

False


In [ ]:
print((2,3) in a8)

False


In [ ]:
print((1,2) in a8)

True


In [ ]:
print(1,2 in a8)

1 True


In [ ]:
print(3 and 4 in a8)

True


In [ ]:
a9 = np.arange(1,16)

In [ ]:
a9

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [ ]:
a10 = a9.reshape(3,5,1) #维度大小乘积 == 元素个数

In [ ]:
a10

array([[[ 1],
        [ 2],
        [ 3],
        [ 4],
        [ 5]],

       [[ 6],
        [ 7],
        [ 8],
        [ 9],
        [10]],

       [[11],
        [12],
        [13],
        [14],
        [15]]])

In [ ]:
print(a10.shape)

(3, 5, 1)


In [ ]:
a11 = a9.reshape(5,3,1)

In [ ]:
a11

array([[[ 1],
        [ 2],
        [ 3]],

       [[ 4],
        [ 5],
        [ 6]],

       [[ 7],
        [ 8],
        [ 9]],

       [[10],
        [11],
        [12]],

       [[13],
        [14],
        [15]]])

In [ ]:
a11.trasports()

AttributeError: 'numpy.ndarray' object has no attribute 'trasports'

In [ ]:
a12 = a11.T

In [ ]:
print(a12)

[[[ 1  4  7 10 13]
  [ 2  5  8 11 14]
  [ 3  6  9 12 15]]]


In [ ]:
a13 = a12.flatten
print(a13())

[ 1  4  7 10 13  2  5  8 11 14  3  6  9 12 15]


In [ ]:
a13 = np.array([(1,2),(3,4),(5,6)])

In [ ]:
a14 = a13[:,np.newaxis,:]

In [ ]:
a14

array([[[1, 2]],

       [[3, 4]],

       [[5, 6]]])

In [ ]:
a14.shape

(3, 1, 2)

In [ ]:
a14[2]

array([[5, 6]])

In [ ]:
a14.flatten()

array([1, 2, 3, 4, 5, 6])

In [ ]:
# 数学操作

In [ ]:
a = np.ones((2,2))
b = np.array([(1,2),(3,4)])
print(a)
print(b)
print()
print(a + b)
print()
print(a - b)
print()
print(a * b)

[[1. 1.]
 [1. 1.]]
[[1 2]
 [3 4]]

[[2. 3.]
 [4. 5.]]

[[ 0. -1.]
 [-2. -3.]]

[[1. 2.]
 [3. 4.]]


In [ ]:
print(a.sum())

4.0


In [ ]:
print(b.prod())

24


In [ ]:
# 数组、矩阵、维度
# 数组、矩阵：数据的组织结构形式
# 维度：数据属性的描述，例子-通讯地址

In [ ]:
a = np.array([(1,2),(3,4)])
print(a.mean())

2.5


In [ ]:
a = np.array([(9.8,6.5),(13.3,41.3)])


In [ ]:
print(a.argmax()) #最大值的索引
print(a.argmin()) #最小值的索引

3
1


In [ ]:
print(np.ceil(a)) #向上取整

[[10.  7.]
 [14. 42.]]


In [ ]:
print(np.floor(a))  #向下取证

[[ 9.  6.]
 [13. 41.]]


In [ ]:
print(np.rint(a)) #四舍五入

[[10.  6.]
 [13. 41.]]


In [ ]:
a16 = np.floor(a) - np.ceil(a)
a16

array([[-1., -1.],
       [-1., -1.]])

In [ ]:
a = np.array([(9.8,6.5),(13.3,41.3)])
a.sort()

In [ ]:
a

array([[ 6.5,  9.8],
       [13.3, 41.3]])

In [ ]:
a = np.array([(1,3,2),(1,72,3),(5,1,3)])

In [ ]:
a.sort()

None


In [ ]:
a

array([[ 1,  2,  3],
       [ 1,  3, 72],
       [ 1,  3,  5]])

In [ ]:
a = np.array([(1,2,3),(4,5,6)])
b = np.array([(7,8),(11,12),(2,3)])

In [ ]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
b

array([[ 7,  8],
       [11, 12],
       [ 2,  3]])

In [ ]:
a * b.T #矩阵乘法计算

array([[ 7, 22,  6],
       [32, 60, 18]])

In [ ]:
c = np.dot(a,b) #矩阵内积计算

In [ ]:
c

array([[ 35,  41],
       [ 95, 110]])

In [ ]:
a @ b 

array([[ 35,  41],
       [ 95, 110]])

In [ ]:
np.save('result.npy',c)

In [ ]:
result_c = np.load('result.npy')
result_c

array([[ 35,  41],
       [ 95, 110]])

In [ ]:
a = np.array([1,2,3])
b = np.array([4,5,6])
c = a + b
c

array([5, 7, 9])

In [ ]:
a = np.array([(1,2,3,0),(2,3,4,5)])
b = np.array([(4,5,6,1)])
c = a + b
print(c)
print(np.shape(a))
np.shape(b)

[[ 5  7  9  1]
 [ 6  8 10  6]]
(2, 4)


(1, 4)

In [ ]:
import numpy as np

In [ ]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [ ]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
b = np.array([(1,2,3),(4,5,6),(7,8,9)])

In [ ]:
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
a = np.zeros((3,3,4),dtype = np.int32)

In [ ]:
a

array([[[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]],

       [[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]],

       [[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]]])

In [ ]:
b = np.ones((3,3,4),dtype = np.float32)

In [ ]:
b

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]], dtype=float32)

In [ ]:
c = np.random.randn(3,3,4)

In [ ]:
c

array([[[0.17097444, 0.24200197, 0.32730069, 0.07277818],
        [0.51252129, 0.8294985 , 0.58738137, 0.43550694],
        [0.80853994, 0.87257934, 0.70293582, 0.29140974]],

       [[0.63506937, 0.8583173 , 0.70025288, 0.09429447],
        [0.49761895, 0.16365973, 0.85266197, 0.85166221],
        [0.6074141 , 0.78867818, 0.28589926, 0.54286998]],

       [[0.6155558 , 0.12706507, 0.41352555, 0.65771189],
        [0.06797713, 0.64477068, 0.26379208, 0.19721276],
        [0.40339325, 0.26840835, 0.57842339, 0.47181958]]])

In [ ]:
b = np.ones((3,3),dtype = np.float64)

In [ ]:
b

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
a = np.arange(1,10,0.2)

In [ ]:
a

array([1. , 1.2, 1.4, 1.6, 1.8, 2. , 2.2, 2.4, 2.6, 2.8, 3. , 3.2, 3.4,
       3.6, 3.8, 4. , 4.2, 4.4, 4.6, 4.8, 5. , 5.2, 5.4, 5.6, 5.8, 6. ,
       6.2, 6.4, 6.6, 6.8, 7. , 7.2, 7.4, 7.6, 7.8, 8. , 8.2, 8.4, 8.6,
       8.8, 9. , 9.2, 9.4, 9.6, 9.8])

In [ ]:
b = np.eye(5,5) #one-hot编码，

In [ ]:
b

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [ ]:
c = np.random.random(4) #可以用于模型参数的初始值
c

array([0.36315959, 0.98251242, 0.31977677, 0.1705984 ])

In [ ]:
d = np.random.random(9)
d

array([0.03765952, 0.08327433, 0.07671387, 0.74775558, 0.60901909,
       0.44653169, 0.53779837, 0.13782618, 0.19206859])

In [ ]:
mu,sigma = 0,0.001

In [ ]:
f = np.random.normal(mu,sigma,5) #可以用于模型参数的初始值
f

array([ 0.00019267, -0.00023557, -0.00165811, -0.00046982,  0.00051813])

In [ ]:
e = np.random.normal(0,0.001,10)
e

array([0.00030778, 0.00104093, 0.00039979, 0.00011567, 0.0009627 ,
       0.00015163, 0.00050279, 0.00040835, 0.00099554, 0.00034328])

In [ ]:
e[:] 

array([0.00030778, 0.00104093, 0.00039979, 0.00011567, 0.0009627 ,
       0.00015163, 0.00050279, 0.00040835, 0.00099554, 0.00034328])

In [ ]:
a = np.array([(1,2),(3,4),(5,6)])

In [ ]:
a[1:] #支持索引访问及切片

array([[3, 4],
       [5, 6]])

In [ ]:
a.ndim #数组维度

2

In [ ]:
a.shape #数组的行列

(3, 2)

In [ ]:
a.size #数组的大小

6

In [ ]:
a.dtype #数组的数据类型

dtype('int32')

In [ ]:
2 in a  #检查元素是否存在数组中，包括多维元素

True

In [ ]:
(2,3,2) in a 

ValueError: operands could not be broadcast together with shapes (3,2) (3,) 

In [ ]:
(1,2) in a

True

In [ ]:
a = np.zeros((3,3,4),dtype = np.float32)

In [ ]:
a

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]], dtype=float32)

In [ ]:
a.reshape(4,3,3) #.reshape能把数组重组为笛卡尔乘积相等的另一个数组

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]], dtype=float32)

In [ ]:
a1 = np.arange(1,10)

In [ ]:
a1

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
a1.size

9

In [ ]:
b = a1.reshape(3,3,1)
b

array([[[1],
        [2],
        [3]],

       [[4],
        [5],
        [6]],

       [[7],
        [8],
        [9]]])

In [ ]:
#img.shape = [1,3,120,120] 1个样本，3个颜色特征通道，120高，120宽

In [ ]:
a1

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
b.transpose()

array([[[1, 4, 7],
        [2, 5, 8],
        [3, 6, 9]]])

In [ ]:
b.T

array([[[1, 4, 7],
        [2, 5, 8],
        [3, 6, 9]]])

In [ ]:
b

array([[[1],
        [2],
        [3]],

       [[4],
        [5],
        [6]],

       [[7],
        [8],
        [9]]])

In [ ]:
c = b.transpose()

In [ ]:
c

array([[[1, 4, 7],
        [2, 5, 8],
        [3, 6, 9]]])

In [ ]:
d = c.flatten()

In [ ]:
d

array([1, 4, 7, 2, 5, 8, 3, 6, 9])

In [ ]:
e = c.reshape(c.size) 

In [ ]:
e

array([1, 4, 7, 2, 5, 8, 3, 6, 9])

In [ ]:
d == e

array([ True,  True,  True,  True,  True,  True,  True,  True,  True])

In [ ]:
d is e

False

In [ ]:
r = c.ravel()

In [ ]:
r

array([1, 4, 7, 2, 5, 8, 3, 6, 9])

In [ ]:
r == d

array([ True,  True,  True,  True,  True,  True,  True,  True,  True])

In [ ]:
r is d

False

In [ ]:
r[0] = 3

In [ ]:
r

array([3, 4, 7, 2, 5, 8, 3, 6, 9])

In [ ]:
c

array([[[1, 4, 7],
        [2, 5, 8],
        [3, 6, 9]]])

In [ ]:
e[1]= 123

In [ ]:
e

array([  1, 123,   7,   2,   5,   8,   3,   6,   9])

In [ ]:
c

array([], shape=(1, 1, 0, 1, 1, 1, 1, 1, 3, 3), dtype=int32)

In [ ]:
d[-1] = 123

In [ ]:
d

array([  1,   4,   7,   2,   5,   8,   3,   6, 123])

In [ ]:
c

array([], shape=(1, 1, 0, 1, 1, 1, 1, 1, 3, 3), dtype=int32)

In [ ]:
c.shape

(1, 1, 0, 1, 1, 1, 1, 1, 3, 3)

In [ ]:
c = c[:,:,np.newaxis == -2] #动态添加维度

In [ ]:
c.shape

(1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 3, 3)

In [ ]:
c

array([], shape=(1, 1, 0, 1, 1, 1, 1, 1, 3, 3), dtype=int32)

In [ ]:
a = np.array([[1,2],[3,4],[5,6]])
b = np.ones((3,2))

In [ ]:
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [ ]:
b

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [ ]:
a + b

array([[2., 3.],
       [4., 5.],
       [6., 7.]])

In [ ]:
d=a @ b.T

In [ ]:
a - b

array([[0., 1.],
       [2., 3.],
       [4., 5.]])

In [ ]:
np.matmul(a,b.T)

array([[ 3.,  3.,  3.],
       [ 7.,  7.,  7.],
       [11., 11., 11.]])

In [ ]:
a.sum() #所有元素的加和

21

In [ ]:
a.prod() #所有元素的乘积

720

In [ ]:
a.mean() #均值

3.5

In [ ]:
a.var() #方差

2.9166666666666665

In [ ]:
a.std() #标准差

1.707825127659933

In [ ]:
a.max() #最大值

6

In [ ]:
a.min() #最小值

1

In [ ]:
d

array([[ 3.,  3.,  3.],
       [ 7.,  7.,  7.],
       [11., 11., 11.]])

In [ ]:
# 定位元素的位置
d.argmax() #最大值的索引位置

6

In [ ]:
d.argmin()#最小值的索引位置

0

In [ ]:
np.ceil(d)

array([[ 3.,  3.,  3.],
       [ 7.,  7.,  7.],
       [11., 11., 11.]])

In [ ]:
a = np.random.rand(1,10)

In [ ]:
a

array([[0.86118216, 0.32208248, 0.72521527, 0.76791214, 0.15965844,
        0.76261774, 0.21655902, 0.99492293, 0.1215449 , 0.74380468]])

In [ ]:
np.ceil(a) #向上取整

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [ ]:
np.floor(a) #向下取整

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [ ]:
np.rint(a) #四舍五入

array([[1., 0., 1., 1., 0., 1., 0., 1., 0., 1.]])

In [ ]:
a.sort() #正向排序

In [ ]:
a

array([[0.1215449 , 0.15965844, 0.21655902, 0.32208248, 0.72521527,
        0.74380468, 0.76261774, 0.76791214, 0.86118216, 0.99492293]])

In [ ]:
a.sort(reverse = True)

TypeError: sort() got an unexpected keyword argument 'reverse'

In [ ]:
# abs、sign、sqrt、log、log10、exp\sin\cos\tan\arcsin\arccos\arctan\sinh\cosh\tanh\arcsinh\arccosh\arctanh