In [11]:
import torch
import numpy as np
from torchviz import make_dot
import torch.nn as nn

计算图：所有深度学习框架（包括pytorch和TensorFlow）对计算图都有依赖，用来完成梯度下降（即求导），优化梯度等计算。!有向无环图!

计算图的创建包含两部分：
1、用户构建前向传播图
2、框架处理后向传播（梯度更新）

包括两种：
1、静态计算图：TensorFlow1.X使用，
两个阶段：
1，定义一个架构（使用一些基本的流控制方法，比如循环和条件指令）
2、


2、动态计算图：TensorFlow2.x和pytorch使用
执行正向计算时，隐式的定义图（动态构建）
优点：灵活，侵入性小，允许动态构建和评估
缺点：难以优化

比较：动态计算图更友好，允许逐行执行代码调试，可以访问所有张量，便于分析过程中的问题。

In [ ]:
# 计算 x^T *A + b * x +c

In [ ]:
A = torch.randn(10,10,requires_grad = True)
x = torch.randn(10,requires_grad = True)
b = torch.randn(1,requires_grad = True)
c = torch.randn(10,requires_grad = True)
result = torch.matmul(A,x) + x * b + c
make_dot(result, params={'A': A, 'x': x,'b': b,'c': c}).render("graph", format="png")

'graph.png'

In [18]:
A = torch.randn(10, 10, requires_grad=True)
x = torch.randn(10, requires_grad=True)
b = torch.randn(1, requires_grad=True)
c = torch.randn(10, requires_grad=True)

# 修正矩阵乘法和维度问题
term1 = torch.matmul(A, x)          # 正确矩阵-向量乘法 (10,10) @ (10,) → (10,)
term2 = x * b                       # 逐元素乘法 (10,) * (1,) → (10,)
result = term1 + term2 + c          # 所有项形状为 (10,)

# 生成计算图
make_dot(result, params={'A': A, 'x': x, 'b': b, 'c': c}).render("graph2", format="png")

'graph2.png'

In [9]:
A

tensor([[ 0.3186,  0.7454, -0.0154,  0.3127,  0.9157,  1.1265, -0.6962,  1.0130,
         -0.6494, -0.7287],
        [ 1.9336, -0.1611, -0.6266, -1.5182, -1.2276, -2.0333, -0.9608, -1.5453,
          2.2191, -0.5200],
        [-0.7021,  0.4765, -0.4799,  0.7325, -0.9601,  1.3206,  0.0779, -1.3229,
          0.7701,  1.0585],
        [-0.8512, -0.5709,  0.1743,  0.4065, -1.5327, -0.0700,  0.5847,  0.6792,
          1.5213, -2.0923],
        [ 0.8228, -0.9738, -0.2882,  0.5834, -0.4781,  1.5311,  2.2954,  2.3473,
         -0.0648, -0.5406],
        [ 0.4783,  1.6168, -0.2780, -0.0600, -2.5612,  1.1720,  0.0178,  0.2687,
          1.6955, -2.4262],
        [-0.5972,  0.2397,  0.7952,  0.0935,  1.1756,  1.4180, -0.6185, -0.8614,
          1.9987,  1.6267],
        [ 0.3105, -0.5855, -0.4719, -1.7612,  0.7601, -0.1554, -0.4618,  0.6943,
          0.3179, -0.5331],
        [-0.5121,  1.7584, -1.3810, -0.7066, -0.0194,  1.1660,  0.6990,  1.1199,
          0.8940,  0.3906],
        [-0.0545, -

In [10]:
x

tensor([ 0.8074,  0.4486,  0.9045,  0.4789,  0.7230,  0.7245, -0.1680, -0.4678,
        -1.3455,  1.5993], requires_grad=True)

In [11]:
b

tensor([-0.4164], requires_grad=True)

In [12]:
c

tensor([-1.1022, -0.8163, -0.1206, -0.2938,  0.1579, -0.9608, -3.0154, -1.4459,
         0.9075,  0.9205], requires_grad=True)

In [19]:
model = nn.Linear(3, 1)          # 简单线性模型
optimizer = torch.optim.SGD(model.parameters(), lr=0.01)
criterion = nn.MSELoss()

# 模拟数据
x = torch.randn(10, 3)           # 10个样本，3维特征
y_true = torch.randn(10, 1)      # 真实值

for epoch in range(100):
    # 前向传播
    y_pred = model(x)
    loss = criterion(y_pred, y_true)
    
    # 反向传播
    optimizer.zero_grad()        # 清空梯度
    loss.backward()              # 计算梯度
    optimizer.step()             # 更新参数
    
    print(f"Epoch {epoch}, Loss: {loss.item()}")

Epoch 0, Loss: 0.2763161063194275
Epoch 1, Loss: 0.2729295790195465
Epoch 2, Loss: 0.269633024930954
Epoch 3, Loss: 0.2664233148097992
Epoch 4, Loss: 0.26329755783081055
Epoch 5, Loss: 0.26025280356407166
Epoch 6, Loss: 0.2572864592075348
Epoch 7, Loss: 0.25439584255218506
Epoch 8, Loss: 0.2515784204006195
Epoch 9, Loss: 0.2488318383693695
Epoch 10, Loss: 0.24615375697612762
Epoch 11, Loss: 0.24354195594787598
Epoch 12, Loss: 0.24099428951740265
Epoch 13, Loss: 0.23850873112678528
Epoch 14, Loss: 0.2360832691192627
Epoch 15, Loss: 0.23371610045433044
Epoch 16, Loss: 0.2314053326845169
Epoch 17, Loss: 0.22914919257164001
Epoch 18, Loss: 0.22694608569145203
Epoch 19, Loss: 0.22479434311389923
Epoch 20, Loss: 0.2226923704147339
Epoch 21, Loss: 0.220638707280159
Epoch 22, Loss: 0.21863193809986115
Epoch 23, Loss: 0.21667058765888214
Epoch 24, Loss: 0.21475335955619812
Epoch 25, Loss: 0.21287901699543
Epoch 26, Loss: 0.21104618906974792
Epoch 27, Loss: 0.20925378799438477
Epoch 28, Loss: 0.

In [20]:
# 定义张量并启用梯度追踪（requires_grad = True）
a = torch.tensor([[2.,3],[1,2]],requires_grad = True)
b = torch.tensor([[2.,4],[2,4]],requires_grad = True)
# 执行前向计算
x = a + b
y = a + 1
z = x * y

# 反向传播生成梯度
# z.backward() #自动构建反向计算图并计算梯度
print(a.grad)
make_dot(z,params = {'a': a,'b': b,'x': x,'y': y}).render('Gragh0203',format = 'svg')

None


'Gragh0203.svg'

In [21]:
a[:]

tensor([[2., 3.],
        [1., 2.]], grad_fn=<SliceBackward0>)

In [22]:
b

tensor([[2., 4.],
        [2., 4.]], requires_grad=True)

In [23]:
x

tensor([[4., 7.],
        [3., 6.]], grad_fn=<AddBackward0>)

In [21]:
y

tensor([[3., 4.],
        [2., 3.]], grad_fn=<AddBackward0>)

In [ ]:
z

tensor([[12., 28.],
        [ 6., 18.]], grad_fn=<MulBackward0>)

In [25]:
print(b.grad)

None


In [24]:
print(x.grad)

None


/var/folders/y0/n5wqv40d02x9388r8gpfwnwh0000gn/T/ipykernel_7635/3014308063.py:1: UserWarning: The .grad attribute of a Tensor that is not a leaf Tensor is being accessed. Its .grad attribute won't be populated during autograd.backward(). If you indeed want the .grad field to be populated for a non-leaf Tensor, use .retain_grad() on the non-leaf Tensor. If you access the non-leaf Tensor by mistake, make sure you access the leaf Tensor instead. See github.com/pytorch/pytorch/pull/30531 for more informations. (Triggered internally at /Users/runner/work/pytorch/pytorch/pytorch/build/aten/src/ATen/core/TensorBody.h:494.)
  print(x.grad)


In [26]:
tensor_5d = torch.randn(2, 3, 4, 5, 6) 

In [ ]:
print(tensor_5d)

tensor([[[[[-5.0507e-01,  1.3760e+00,  6.2859e-02,  6.2422e-01,  3.4300e-01,
             1.8170e+00],
           [ 5.2881e-01, -1.0835e+00, -1.9930e-01, -1.3299e+00, -1.8179e+00,
            -3.5896e-01],
           [ 5.0085e-01, -1.4668e+00, -1.5478e+00,  2.6576e+00,  9.8478e-01,
            -8.4839e-02],
           [ 1.4319e-01,  6.0850e-01, -1.7206e+00,  6.3546e-01, -7.0675e-01,
             1.4928e+00],
           [-1.5929e+00, -8.0243e-02,  1.7190e+00,  4.1433e-01, -2.0838e-02,
            -2.9645e-01]],

          [[ 3.3359e-01, -7.6419e-01,  5.2839e-02,  8.2943e-01, -5.5312e-01,
            -1.6398e+00],
           [-2.0488e+00, -4.1051e-01, -1.5896e-01,  1.3283e+00,  1.2193e-01,
             1.6724e+00],
           [-6.4176e-01, -7.6400e-01, -1.2524e+00,  1.5526e+00, -1.8178e+00,
             1.0252e+00],
           [ 6.7805e-01,  6.0931e-01, -3.0526e-01,  1.4654e+00, -3.0490e-01,
             4.0776e-01],
           [-8.5960e-01, -4.3125e-01, -7.6969e-01,  9.1948e-01, -2.9745

In [25]:
tensor_5d.shape

torch.Size([2, 3, 4, 5, 6])

In [26]:
tensor_5d.reshape = 2,3,4

In [27]:
tensor_5d.shape

torch.Size([2, 3, 4, 5, 6])

In [15]:
from graphviz import Digraph

In [27]:
dot = Digraph()
dot.node('A', 'Test')
dot.render('test.gv', format='png')

'test.gv.png'